spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EduCity
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lihe7524337

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    root: info    # ????????info
    com.EduCity: debug    # ??com.EduCity????????debug

mail:
  user: EduCity2023@gmail.com
  password: 2023EduCity



